-----------------------------------------------------
-- This file is automatically generated by matugen --
-----------------------------------------------------

local M = {}

<* for name, value in colors *>
M.{{name}} = "rgba({{value.default.hex_stripped}}ff)"<* endfor *>

return M
