-----------------------------------------------------
-- This file is automatically generated by matugen --
-----------------------------------------------------

local M = {}

<* for name, value in colors *>
M.{{name}} = "{{value.default.hex}}"<* endfor *>

return M
